spring:
  datasource:
    url: jdbc:mysql://localhost:3306/petlog
    username: root
    password: rootpassword
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mappers/*.xml # resources/mapper/...
  type-aliases-package: com.petlog.userService.domain

jwt:
  secret:
    key: ${JWT_SECRET_KEY:7Leo7JeF7L2U7Iqk7ZmU7J207YyF7ZW064u56rWQ7Jyh6rO87KCV7J2E64Gd64K06rOg64KY66m06ryt7Leo7JeF7ZWY7Iuk7IiY7J6I7J2E6rKB64uI64ukLg}

