spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mappers/*.xml # resources/mapper/...
  type-aliases-package: com.petlog.userService.domain

jwt:
  secret:
    key: ${JWT_SECRET_KEY}

aws:
  s3:
    bucket: ${AWS_S3_BUCKET}  # S3 버킷 이름
  credentials:
    accessKey: ${AWS_S3_CREDENTIALS_ACCESSKEY}  #️ IAM 사용자 Access Key
    secretKey: ${AWS_S3_CREDENTIALS_SECRETKEY}  # IAM 사용자 Secret Key
  region: ap-northeast-2  # 사용 중인 AWS 리전 (서울 기준)